### ISSUE TITLE
No issue. Just compliment.

### ISSUE THREAD

**Issue by TheSashmo** [ricardorodrigues-ca/zoom-recording-downloader#11]
Great tool.  Love it.

I am super admin, and its downloaded everyones cloud recordings.

Would be great to see the option to delete, or some other way to pause/continue the process.

I am to assume that if it has been downloaded and logged, that the file wont download again if I run the script again?
edit** yup! it does do that......

edit**  maybe an index option to get the file sizes of total space needed to download everything! I've got 640 more to go, not sure if I will have enough HDD space!

Great work man!

**Comment by alborworld** [comment]
Thanks a lot also from my side! 

I forked the project and dockerized it (https://github.com/alborworld/zoom-recording-downloader) to download recordings to my Synology Diskstation, as I want to keep them all there. So far it works like a charm!

**Comment by ricardorodrigues-ca** [comment]
Love it -- great work!
