### ISSUE TITLE
Zoom to AWS S3

### ISSUE THREAD

**Issue by skyricho** [ricardorodrigues-ca/zoom-recording-downloader#12]
Hi mate

Are you interest in a Python gig?

I would like a tool that recieves the zoom webhook that a zoom cloud recording is ready, then uploads the file to AWS s3 and then sends an email notification that the file once the file has finished being uploaded.

**Comment by ricardorodrigues-ca** [comment]
Hi, thanks for the offer, but I'm not in that line of work at the moment.

Feel free to fork the project and reach out to someone on Fiverr.com for help.

Cheers.

RR

**Comment by skyricho** [comment]
Thanks for getting back to me. Great project by the way.
