### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by baaoh** [ricardorodrigues-ca/zoom-recording-downloader#2]
Hi, thanks for creating this, it has some potential to save me a lot of work.

I took all the steps you described, but I got stuck at this error:
`Getting user accounts...
Traceback (most recent call last):
  File "zoom-recording-downloader.py", line 270, in <module>
    main()
  File "zoom-recording-downloader.py", line 223, in main
    users = get_user_ids()
  File "zoom-recording-downloader.py", line 80, in get_user_ids
    total_pages = int(page_data['page_number']) + 1
KeyError: 'page_number'
`
I don't know what to do, ask me whatever and I'll try to provide all information

Thanks

**Comment by ricardorodrigues-ca** [comment]
Hi,

What did you put for your RECORDING_START_DATE ?

- Ricardo

**Comment by baaoh** [comment]
Hi Ricardo,

I've made it work, the issue was, I was not using the correct token - I used the API Key, instead of the JWT Token.
Also the JWT Token needs to be valid, since by default it expires in 90 minutes. (But the expiration time can be set).
So to me this was not clear (I didn't read correctly)

I've managed to download some recordings - will this tool download ALL recordings from ALL acccounts? (within the set time period) OR are there any limitations that I should know

Thanks!

**Comment by ricardorodrigues-ca** [comment]
Hey, that's great news. I'm glad you were able to locate the problem. 

Let me know if there is anything you feel I should add to the README instructions.

The script will grab a list of all users in your Zoom account, then parse all their cloud recordings and download them (within the given date range). Keep in mind that it can only fetch recordings within a 6 month range.

Cheers,

Ricardo Rodrigues
