### ISSUE TITLE
JWT will be deprecated from Zoom API

### ISSUE THREAD

**Issue by meadow-kun** [ricardorodrigues-ca/zoom-recording-downloader#22]
<img width="813" alt="Screenshot 2022-09-16 at 13 29 58" src="https://user-images.githubusercontent.com/2424351/190629306-bad2b0a1-d3ca-488d-8f4b-654ea9642aec.png">

Just a heads up that this implementation will run into issues by June 2023. 

Cloned today, worked flawlessly. Thank you!

**Comment by alexknowshtml** [comment]
Has anybody successfully updated this to use Server-to-server instead of JWT?

**Comment by freelimiter** [comment]
> Has anybody successfully updated this to use Server-to-server instead of JWT?

Yes!

**Comment by alexknowshtml** [comment]
@freelimiter let me know if I can help test!

**Comment by freelimiter** [comment]
> @freelimiter let me know if I can help test!

`def load_access_token():

    url = "https://zoom.us/oauth/token?grant_type=account_credentials&account_id=" + ACCOUNT_ID

    client_cred = CLIENT_ID + ":" + CLIENT_SECRET
    client_cred_base64_string = base64.b64encode(client_cred.encode('utf-8')).decode('utf-8')

    headers = {
      'Authorization': 'Basic ' + client_cred_base64_string,
      'Content-Type': 'application/x-www-form-urlencoded'
    }

    response = requests.request("POST", url, headers=headers)

    jdata = json.loads(response.text)

    global ACCESS_TOKEN
    global AUTHORIZATION_HEADER

    ACCESS_TOKEN = jdata["access_token"]
    AUTHORIZATION_HEADER = {'Authorization': 'Bearer ' + ACCESS_TOKEN,
                            'Content-Type': 'application/json'}
`

**Comment by freelimiter** [comment]
``def load_access_token():

    url = "https://zoom.us/oauth/token?grant_type=account_credentials&account_id=" + ACCOUNT_ID

    client_cred = CLIENT_ID + ":" + CLIENT_SECRET
    client_cred_base64_string = base64.b64encode(client_cred.encode('utf-8')).decode('utf-8')

    headers = {
      'Authorization': 'Basic ' + client_cred_base64_string,
      'Content-Type': 'application/x-www-form-urlencoded'
    }

    response = requests.request("POST", url, headers=headers)

    jdata = json.loads(response.text)

    global ACCESS_TOKEN
    global AUTHORIZATION_HEADER

    ACCESS_TOKEN = jdata["access_token"]
    AUTHORIZATION_HEADER = {'Authorization': 'Bearer ' + ACCESS_TOKEN,
                            'Content-Type': 'application/json'}
``

**Comment by freelimiter** [comment]
I'm such a noob. sorry.
Add ACCOUNT_ID, CLIENT_ID, CLIENT_SECRET at the top where the global vars are.

Then in the main function, insert load_access_token() before load_completed_meeting_ids()

**Comment by freelimiter** [comment]
also import base64

**Comment by freelimiter** [comment]
> @freelimiter let me know if I can help test!

Does it work for you?

**Comment by alexknowshtml** [comment]
Giving this a go tomorrow morning, will let you know. Thank you for sharing!

**Comment by alexknowshtml** [comment]
@freelimiter - followed your instructions, getting this:
```
Traceback (most recent call last):
  File "/Users/alexhillman/Desktop/zoom-recording-downloader/zoom-recording-downloader.py", line 319, in <module>
    main()
  File "/Users/alexhillman/Desktop/zoom-recording-downloader/zoom-recording-downloader.py", line 264, in main
    load_access_token()
  File "/Users/alexhillman/Desktop/zoom-recording-downloader/zoom-recording-downloader.py", line 81, in load_access_token
    jdata = json.loads(response.text)
NameError: name 'json' is not defined
```

**Comment by freelimiter** [comment]
Add “import json” at the top

**Comment by freelimiter** [comment]
Ok May need some error checking in that part of the code. But did you
create a new App in zoom for Server to server OAuth and then filled out all
credentials in the global  variables?

**Comment by alexknowshtml** [comment]
Good news! I didn't realize that I hadn't finished setting up the S2S Oauth App, I just copied the credentials from the first panel. 

While completing the app creation, I did some guess and check and got the script working by adding the scopes for downloads, users, and accounts. Once I had them done, the app worked again! Thanks so much for this. 

<img width="441" alt="Monosnap M2 Mini 2023-05-18 10-08-37" src="https://github.com/ricardorodrigues-ca/zoom-recording-downloader/assets/3707/83dbdb8f-eaf4-44a7-8bf8-974b0918786a">

Any idea which ones are actually needed, so I can remove the rest?

**Comment by freelimiter** [comment]
That great! It’s all about trial and error at this point. Glad it’s working
out for you!

**Comment by Xac1** [comment]
Hi. Can you please give the updated to Server-to-server code? Thanks.

**Comment by risdian** [comment]
care to share the source code?

**Comment by freelimiter** [comment]
read this entire thread. 

> care to share the source code?

**Comment by neylwalecki** [comment]
Hi folks, I've been using this acript for a while and has saved my life! Thanks for the update @freelimiter
I've just submitted my first pull request ever, with the updated code. Hope I've done everything right.
:-)

**Comment by freelimiter** [comment]
Oh awesome! I was going to do it but got busy. Thanks!!!

**Comment by neylwalecki** [comment]
@risdian you can check the changes/new code here https://github.com/ricardorodrigues-ca/zoom-recording-downloader/pull/37/files

**Comment by risdian** [comment]
> @risdian you can check the changes/new code here https://github.com/ricardorodrigues-ca/zoom-recording-downloader/pull/37/files

i already done the code. thanks to @freelimiter. thank you all.

**Comment by freelimiter** [comment]
`def delete_meeting(meeting_id):
    # Delete the recording
    delete_url = "https://api.zoom.us/v2/meetings/{}/recordings".format(meeting_id)
    response = requests.delete(delete_url, headers=AUTHORIZATION_HEADER)

    if response.status_code == 204:
        print("Successfully deleted recording for meeting: {}".format(meeting_id))
    else:
        print("Failed to delete recording for meeting: {}. Response: {}".format(meeting_id, response.text))
`

**Comment by freelimiter** [comment]
``def delete_meeting(meeting_id):
    # Delete the recording
    delete_url = "https://api.zoom.us/v2/meetings/{}/recordings".format(meeting_id)
    response = requests.delete(delete_url, headers=AUTHORIZATION_HEADER)

    if response.status_code == 204:
        print("Successfully deleted recording for meeting: {}".format(meeting_id))
    else:
        print("Failed to delete recording for meeting: {}. Response: {}".format(meeting_id, response.text))

**Comment by freelimiter** [comment]
def delete_meeting(meeting_id):
    # Delete the recording
    delete_url = "https://api.zoom.us/v2/meetings/{}/recordings".format(meeting_id)
    response = requests.delete(delete_url, headers=AUTHORIZATION_HEADER)

    if response.status_code == 204:
        print("Successfully deleted recording for meeting: {}".format(meeting_id))
    else:
        print("Failed to delete recording for meeting: {}. Response: {}".format(meeting_id, response.text))

**Comment by freelimiter** [comment]
also added new function called delete_meeting.  You can call this function after "skipping already downloaded" and the "# if successful, write the ID of this recording to the completed file". hope that makes sense.


def delete_meeting(meeting_id):
    # Delete the recording
    delete_url = "https://api.zoom.us/v2/meetings/{}/recordings".format(meeting_id)
    response = requests.delete(delete_url, headers=AUTHORIZATION_HEADER)

    if response.status_code == 204:
        print("Successfully deleted recording for meeting: {}".format(meeting_id))
    else:
        print("Failed to delete recording for meeting: {}. Response: {}".format(meeting_id, response.text))

**Comment by ricardorodrigues-ca** [comment]
Script now uses Server-to-Server OAuth authentication, and updated README.md to reflect new instructions.
