### ISSUE TITLE
Cannot see Zoom Room users

### ISSUE THREAD

**Issue by kyleboddy** [ricardorodrigues-ca/zoom-recording-downloader#43]
I am using the script and have had success authenticating, but no recordings show up for the Zoom Room I run on that account as admin. There is an autogenerated email like rooms_xxxx@gmail.com that is the "owner" of that account but it's under my license.

Any ideas how to see those recordings? I see them in the Admin page but not the script via API.

**Comment by ricardorodrigues-ca** [comment]
Support for Zoom Room accounts is not available at this current time.
