### ISSUE TITLE
Trouble with OAuth Redirect URL

### ISSUE THREAD

**Issue by mingomongo** [ricardorodrigues-ca/zoom-recording-downloader#45]
What am I supposed to set the "Redirect URL for OAuth" to in the app credentials? Is there something I need to set up? New to this.

**Comment by ricardorodrigues-ca** [comment]
The script only needs three credentials from you: `Account ID`, `Client ID`, and `Client Secret`. 

Are you setting up a **Server-to-Server OAuth** app, or a simple **OAuth** app? It has to be Server-to-Server OAuth.
