### ISSUE TITLE
Help please to start app

### ISSUE THREAD

**Issue by abel1534** [ricardorodrigues-ca/zoom-recording-downloader#48]
Hello 

Thank You so much for putting together this app. I was thinking I needed to write the code myself before I stumbled upon your repo. It is soooo helpful. Thank You

I am on a Windows machine and I am getting this error when trying to run the app(I have masked credentials). Any thoughts?
I appreciate your help.
Thank you

![image](https://github.com/ricardorodrigues-ca/zoom-recording-downloader/assets/24769536/8cebc7e1-b8e7-4432-8815-b9a1f01910fd)

**Comment by behanw** [comment]
On line 9 of your file you've ended the line with a comma. Sadly your configuration isn't valid JSON as written.

I suggest using json lint or https://jsonformatter.curiousconcept.com/ to validate your JSON.

I hope this helps.

**Comment by jmsapps** [comment]
Yes, as [behanw](https://github.com/behanw) pointed out, there is a typo on line 9. Since the configuration template is valid JSON I am going to close this issue as completed.
