### ISSUE TITLE
Process halting midway through recording downloads

### ISSUE THREAD

**Issue by dmccreton** [ricardorodrigues-ca/zoom-recording-downloader#9]
After running continuously and having the script go through our user database it seems to always stop at the exact same point in the user list and gives out an error and the process stops.

The error I receive is:

Traceback (most recent call last):
  File "zoom-recording-downloader.py", line 270, in <module>
    main()
  File "zoom-recording-downloader.py", line 241, in main
    downloads = get_downloads(recording)
  File "zoom-recording-downloader.py", line 108, in get_downloads
    for download in recording['recording_files']:
KeyError: 'recording_files'

**Comment by ricardorodrigues-ca** [comment]
It's most likely failing on a particular user account. The question is "why"? What's in the recording data for that user?

The quickest thing to check for is if there are any odd characters (colon, semi-colon, forward slash, backslash, etc.) in the recording titles.
Second is to use the [Send a Test Request](https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/recordingslist) feature on Zoom's website to get all the recordings for that particular user. Look at the data it returns - see anything unusual or out of place?
